name: Build Wheels
run-name: ${{ github.event_name == 'workflow_dispatch' && 'Manual Build Wheels' || github.ref_type == 'tag' && format('Build Wheels for tag {0}', github.ref_name) || format('Build Wheels for {0}', github.ref_name) }}

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual triggering


jobs:

  # Build wheels on Linux
  build_linux_wheels:
    name: Build python ${{ matrix.cibw_python }} ${{matrix.cibw_arch}} wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cibw_python: ["cp312-*", "cp313-*"]
        cibw_arch: ["x86_64", "aarch64"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up QEMU
        if: ${{ matrix.cibw_arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Install build dependencies
        shell: bash
        run: |
          python -m pip install numpy>=2.0.0 meson-python

      - name: Build the wheel
        shell: bash
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
          CIBW_SKIP: "*-musllinux*"
          CIBW_TEST_SKIP: "*"
      
      - name: Rename python version
        shell: bash
        run: |
          echo "PY_VERSION=$(echo ${{ matrix.cibw_python }} | cut -d- -f1)" >> $GITHUB_ENV

      - name: Upload the wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ env.PY_VERSION }}-${{ matrix.os }}-${{ matrix.cibw_arch }}
          path: ./dist/*.whl

  # Build wheels on macOS
  build_osx_wheels:
    name: Build python ${{ matrix.cibw_python }} ${{matrix.cibw_arch}} wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest]
        cibw_python: ["cp312-*", "cp313-*"]
        include:
          - os: macos-latest
            cibw_arch: x86_64
          - os: macos-14
            cibw_arch: arm64
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Install build dependencies
        run: |
          python -m pip install numpy>=2.0.0 meson-python

      - name: Build the wheel
        shell: bash
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS_MACOS: ${{ matrix.cibw_arch }}
          CIBW_TEST_SKIP: "*"

      - name: Rename python version
        shell: bash
        run: |
          echo "PY_VERSION=$(echo ${{ matrix.cibw_python }} | cut -d- -f1)" >> $GITHUB_ENV
      
      - name: Upload the wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ env.PY_VERSION }}-${{ matrix.os }}-${{ matrix.cibw_arch }}
          path: ./dist/*.whl
  

  # Build wheels on Windows
  build_windows_wheels:
    name: Build python ${{ matrix.cibw_python }} ${{matrix.cibw_arch}} wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
        cibw_python: ["cp312-*", "cp313-*"]
        cibw_arch: ["AMD64"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Install build dependencies
        run: |
          python -m pip install numpy>=2.0.0 meson-python

      - name: Build the wheel
        shell: bash
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS_WINDOWS: ${{ matrix.cibw_arch }}

      - name: Rename python version
        shell: bash
        run: |
          echo "PY_VERSION=$(echo ${{ matrix.cibw_python }} | cut -d- -f1)" >> $GITHUB_ENV

      - name: Upload the wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ env.PY_VERSION }}-${{ matrix.os }}-${{ matrix.cibw_arch }}
          path: ./dist/*.whl

  # publish to test pypi
  publish_to_test_pypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/miscgeom
    
    permissions:
      id-token: write
    
    steps:
      - name: Download all dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
